api_info:
  port: 8080
  host: "localhost"
  version: "v1"
  log_level: "debug"

pg_dsn: "postgresql://postgres:postgres@localhost:5432/account_service?sslmode=disable"

kafka_brokers:
  - "localhost:9092"
  - "localhost:9093"
  - "localhost:9094"

kafka:
  brokers:
    - "localhost:9092"
    - "localhost:9093"
    - "localhost:9094"
  consumer:
    group_id: "auth-service.consumer-group"
    topics:
      - "account-service.user.created"