api_info:
  port: 8088
  host: "localhost"
  version: "v1"
  log_level: "debug"

pg_dsn: "postgresql://postgres:postgres@localhost:5432/account_service?sslmode=disable"

kafka:
  brokers:
    - "localhost:8097"
    - "localhost:8098"
    - "localhost:8099"
  consumer:
    group_id: "auth-service.consumer-group"
    topics:
      - "account-service.user.created"